[package]
authors = ["Mathias Koch <mk@blackbird.online>"]
edition = "2018"
categories = ["no-std"]
description = "serde serializer/deserializer for AT commands"
documentation = "https://docs.rs/serde_at"
repository = "https://github.com/BlackbirdHQ/atat"
keywords = ["serde", "AT"]
license = "MIT OR Apache-2.0"
name = "serde_at"
version = "0.1.8-alpha.0"

[dependencies]
heapless = { version = "0.5.3", features = ["serde"] }
log = "0.4.8"

[dependencies.serde]
default-features = false
version = "1.0.104"

[dev-dependencies]
serde_derive = "1.0.104"

[features]
custom-error-messages = []
