[package]
authors = ["Mathias Koch <mk@blackbird.online>"]
edition = "2018"
categories = ["no-std"]
description = "serde serializer/deserializer for AT commands"
documentation = "https://docs.rs/serde_at"
keywords = ["serde", "AT"]
license = "MIT OR Apache-2.0"
name = "serde_at"
version = "0.1.2"

[dependencies]
heapless = "0.5.3"
log = "0.4.8"

[dependencies.serde]
default-features = false
version = "1.0.104"

[dev-dependencies]
serde_derive = "1.0.104"

[features]
custom-error-messages = []
std = ["serde/std"]
