on:
  push:
    branches:    
        - master         # Push events on master branch

name: CodeCoverage

# https://github.com/actions-rs/tarpaulin

jobs:

  code_coverage:
    name: CodeCoverage (stable)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7m-none-eabi
          override: true
      - name: Install Tarpaulin
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-tarpaulin
      - name: Test Code Coverage
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: '-- -test-threads 1'