name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  cancel_previous_runs:
    name: Cancel previous runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: thumbv7m-none-eabi
          override: true

      - name: Build (native - default features)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all

      - name: Build (native - no logging)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --features "derive, std"

      - name: Build (native - log logging)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --features "derive, std, log"

      - name: Build (native - defmt logging)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all 
            --features "
                derive
                std
                defmt-default
                defmt-trace
                defmt-debug
                defmt-info
                defmt-warn
                defmt-error"

      - name: Build (ARM - default features)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all
            --target thumbv7m-none-eabi

      - name: Build (ARM - no logging)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all
            --target thumbv7m-none-eabi
            --features "derive"

      - name: Build (ARM - log logging)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all
            --target thumbv7m-none-eabi
            --features "derive, log"

      - name: Build (ARM - defmt logging)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all
            --target thumbv7m-none-eabi
            --features "
              derive
              defmt-default
              defmt-trace
              defmt-debug
              defmt-info
              defmt-warn
              defmt-error"

      - name: Library tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --lib --all-features
      # TODO: Change this to a single --all test, when the examples work
      - name: Doctests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc --all-features
