[package]
name = "atat"
version = "0.3.0"
authors = ["Mathias Koch <mk@blackbird.online>"]
description = "AT Parser for serial based device crates"
readme = "../README.md"
keywords = ["arm", "cortex-m", "AT", "no-std"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/BlackbirdHQ/atat"
edition = "2018"
documentation = "https://docs.rs/atat"

[lib]
name = "atat"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
embedded-hal = "^0.2"
nb = "^0.1"
void = { version = "^1", default-features = false }
heapless = { version = "0.5.5", features = ["serde"] }
serde_at = { path = "../serde_at", version = "^0.3.0"}
atat_derive = { path = "../atat_derive", version = "^0.3.0", optional = true }
serde = {version = "^1", default-features = false}
log = { version = "^0.4", default-features = false, optional = true }
typenum = "^1"

[dev-dependencies]
cortex-m = "0.6.2"
cortex-m-rt = "0.6.12"
cortex-m-rtfm = "0.5.1"
panic-halt = "0.2.0"
stm32l4xx-hal = { git = "https://github.com/stm32-rs/stm32l4xx-hal", features = ["stm32l4x5", "rt"] }

[features]
default = ["derive"]
derive = ["atat_derive"]
logging = ["log"]
