[package]
name = "atat"
version = "0.18.0"
authors = ["Mathias Koch <mk@blackbird.online>"]
description = "AT Parser for serial based device crates"
readme = "../README.md"
keywords = ["arm", "cortex-m", "AT", "no-std", "embedded-hal-driver"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/BlackbirdHQ/atat"
edition = "2021"
documentation = "https://docs.rs/atat"

[badges]
maintenance = { status = "actively-developed" }

[lib]
name = "atat"

[dependencies]
bincode = { version = "2.0.0-rc.2", default-features = false, features = [
    "derive",
] }
embedded-io = "0.4"
futures = { version = "0.3", default-features = false, optional = true }
embassy-time = "0.1.0"
heapless = { version = "^0.7", features = ["serde"] }
bbqueue = { git = "https://github.com/jamesmunns/bbqueue", rev = "refs/pull/95/head" }
serde_at = { path = "../serde_at", version = "^0.18.0", optional = true }
atat_derive = { path = "../atat_derive", version = "^0.18.0", optional = true }
serde_bytes = { version = "0.11.5", default-features = false, optional = true }
heapless-bytes = { version = "0.3.0", optional = true }

nom = { version = "^7.1", default-features = false }

log = { version = "^0.4", default-features = false, optional = true }
defmt = { version = "^0.3", optional = true }

[features]
default = ["derive", "bytes"]
defmt = ["dep:defmt", "embedded-io/defmt"]
derive = ["atat_derive", "serde_at"]
bytes = ["heapless-bytes", "serde_bytes"]
custom-error-messages = []

async = ["embedded-io/async", "futures"]

thumbv6 = ["bbqueue/thumbv6"]

std = [
    "serde_at/std",
    "nom/std",
    "embassy-time/std",
    "embedded-io/std",
    "embedded-io/tokio",
]
