[package]
name = "atat"
version = "0.13.1"
authors = ["Mathias Koch <mk@blackbird.online>"]
description = "AT Parser for serial based device crates"
readme = "../README.md"
keywords = ["arm", "cortex-m", "AT", "no-std", "embedded-hal-driver"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/BlackbirdHQ/atat"
edition = "2018"
documentation = "https://docs.rs/atat"

[lib]
name = "atat"

[[bench]]
name = "ingress"
harness = false

[[bench]]
name = "client"
harness = false

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
embedded-hal = { version = "=1.0.0-alpha.4" }
nb = "^1"
heapless = { version = "^0.7.0", features = ["serde"] }
serde_at = { path = "../serde_at", version = "^0.13.2-alpha.0", optional = true }
atat_derive = { path = "../atat_derive", version = "^0.13.2-alpha.0", optional = true }
serde_bytes = { version = "0.11.5", default-features = false, optional = true }
heapless-bytes = { version = "0.3.0", optional = true }
bbqueue = "0.5"

log = { version = "^0.4", default-features = false, optional = true }
defmt = { version = "^0.2", optional = true }

[dev-dependencies]
cortex-m = "0.7.1"
cortex-m-rt = "0.6.13"
cortex-m-rtic = "0.5.5"
panic-halt = "0.2.0"
stm32l4xx-hal = { git = "https://github.com/MathiasKoch/stm32l4xx-hal", branch = "enhancement/prepare-embedded-hal-1.0", features = [
    "stm32l4x5",
    "rt",
] }
criterion = { version = "0.3.5" }

[features]
default = ["derive", "bytes"]
derive = ["atat_derive", "serde_at"]

bytes = ["heapless-bytes", "serde_bytes"]

std = ["serde_at/std"]

defmt-default = ["defmt"]
defmt-trace = ["defmt"]
defmt-debug = ["defmt"]
defmt-info = ["defmt"]
defmt-warn = ["defmt"]
defmt-error = ["defmt"]
