[package]
name = "atat"
version = "0.1.8-alpha.0"
authors = ["Mathias Koch <mk@blackbird.online>"]
description = "AT Parser for serial based device crates"
readme = "../README.md"
keywords = ["arm", "cortex-m", "AT", "no-std"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/BlackbirdHQ/atat"
edition = "2018"
documentation = "https://docs.rs/atat"

[lib]
name = "atat"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
embedded-hal = "0.2.3"
nb = "0.1.2"
ufmt = "0.1.0"
heapless = { version = "0.5.3", features = ["serde"] }
serde_at ={ path = "../serde_at" }
serde = {version = "1.0.104", default-features = false}
serde_repr = "0.1.5"
atat_derive = { path = "../atat_derive", optional = true }
# atat_derive = { version = "^0.1.6", optional = true }
log = { version = "0.4", default-features = false }
ticklock = "0.0.8"

[dev-dependencies]
cortex-m = "0.6.2"
cortex-m-rt = "0.6.12"
cortex-m-rtfm = "0.5.1"
panic-halt = "0.2.0"
stm32l4xx-hal = { version = "0.5.0", features = ["stm32l4x5", "rt"] }

[patch.crates-io]
atat_derive = { path = "../atat_derive" }

[target.'x86_64-unknown-linux-gnu'.dev-dependencies]
# env_logger = "0.7.1"
embedded-hal-mock = "0.7.1"

[features]
default = ["derive"]

logging = []
derive = ["atat_derive"]
